seed: 1234
batch_size: 1
num_workers: 4

gpus: 1
accumulate_grad_batches: 1
default_root_dir: /data/home/firas/Desktop/work/other_groups/medicaldiffusion/checkpoints/vq_gan/
default_root_dir_postfix: ''
resume_from_checkpoint:
max_steps: -1
max_epochs: -1
precision: 16
gradient_clip_val: 1.0


embedding_dim: 128
n_codes: 2048
n_hiddens: 128
lr: 1e-4
downsample: [2, 2, 2]
disc_channels: 64
disc_layers: 3
discriminator_iter_start: 100000
disc_loss_type: hinge
image_gan_weight: 0.0
video_gan_weight: 0.0
l1_weight: 1.0
gan_feat_weight: 0.0
perceptual_weight: 0.0
i3d_feat: False
restart_thres: 1.0
no_random_restart: False
norm_type: group
padding_type: replicate
num_groups: 32


